### ISSUE TITLE
Voco feedback played too fast

### ISSUE THREAD

**Issue by rafiksheikh** [createcandle/voco#19]
Hello,
I am trying to install and configure Voco add-on on WebThings Gateway. For this I am using Jabra USB speaker / microphone combo. Speaker and microphone seems to be detected and working fine, I tested it via "aplay " and “record”.

I also here feedback when I say “hey snip” however feedback sound is played very fast. For example if I say “what is current time?” I do hear output but it playbacks very fast and it is hard to understand. If I connect speaker via 3.5mm jack and change Things --> Voice Control --> Audio output --> From " USB Audio" to “Built-in Headphone jack” it works fine.

**Comment by LionMike** [comment]
In the configuration settings of the voco add-on you can change the speed, pitch, and accent of the voice,

**Comment by rafiksheikh** [comment]
I tried all those settings with no success. Please note, I have this problem only if I use USB Audio as output (using USB speaker). Using 3.5mm jack it works with no issue.

**Comment by createcandle** [comment]
Very odd. I don't have one of those devices, so I can't replicate this issue here.

I'm assuming that the .wav files are created correctly (since they play fine though the headphone jack). So the issue must be with the Jabra device, which takes the `aplay` command and somehow plays it at a different rate.

I found this similar issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1282285

So I don't know how to fix this, since it seems to be an issue with the linux support for the Jabra device.

**Comment by rafiksheikh** [comment]
Thanks. In my system I don't have daemon.conf under /etc/pulse.

I am using Raspberry PI with a fresh install of webthings gateway version
1.0 . Will check with another USB audio device.

By the way, when I test the speaker with speaker-test command it works fine.

**Comment by createcandle** [comment]
Webthings Gateway does not have Pulse Audio installed.

This might be more useful if you want to attempt to modify the samplerate settings:

https://askubuntu.com/questions/1298113/set-alsa-frequency-for-a-single-device

which links to

https://unix.stackexchange.com/questions/74558/change-sampling-rate-in-alsa/141234#141234

**Comment by createcandle** [comment]
Since this isn't really an issue with Voco, but with Linux support for your device, I'm closing this issue. I would highly recommend buying the $12 microphone I suggest here:
https://www.candlesmarthome.com/voco-privacy-friendly-voice-control

**Comment by rafiksheikh** [comment]
Thanks!

**Comment by createcandle** [comment]
@rafiksheikh and @kgiori, could you try running this command using the Seashell addon?

`ffplay -nodisp -vn -infbuf -autoexit /tmp/response.wav -volume 100`

It's an alternative audio player. Perhaps that could be an option to implement.

Could you also try this?

`aplay -D plughw:1,0 /tmp/response.wav -r 16000`

If you hear sound, could you also try:

`aplay -D plughw:1,0 /tmp/response.wav -r 44000`
and
`aplay -D plughw:1,0 /tmp/response.wav -r 48000`

...and tell me if any of them sound ok?

Could you also try:

`aplay -D sysdefault:1,0 /tmp/response.wav`

Those commands use the current `aplay`audio player, but with extra parameters that could perhaps force the correct bitrate.

If you don't hear anything, you may have to change the `1,0` into `2,0` in the commands above. So that would look like this:

`aplay -D plughw:2,0 /tmp/response.wav -r 16000`



Also, could you share the output of running this command in Seashell?

`aplay -L`

Another similar issue can be found here: https://github.com/alexylem/jarvis/issues/65

**Comment by kgiori** [comment]
RPi 3 B+ and USB Jabra speaker/mic

results of 'aplay -L' first:
```null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dmix:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Hardware device with all software conversions
default:CARD=USB
    Jabra SPEAK 510 USB, USB Audio
    Default Audio Device
sysdefault:CARD=USB
    Jabra SPEAK 510 USB, USB Audio
    Default Audio Device
front:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Front speakers
surround21:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample mixing device
dsnoop:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct sample snooping device
hw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Direct hardware device without any conversions
plughw:CARD=USB,DEV=0
    Jabra SPEAK 510 USB, USB Audio
    Hardware device with all software conversions

Command success

**Comment by kgiori** [comment]
Command success but no audio at all from:
`ffplay -nodisp -vn -infbuf -autoexit /tmp/response.wav -volume 100`

Too fast to understand from:
`aplay -D plughw:1,0 /tmp/response.wav -r 16000` 
(and all other -r variants sound exactly the same)

This one fails:
`aplay -D sysdefault:1,0 /tmp/response.wav`
with this response:
```Error: ALSA lib conf.c:4898:(parse_args) Unknown parameter 1
ALSA lib conf.c:5031:(snd_config_expand) Parse arguments error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault:1,0
aplay: main:828: audio open error: No such file or directory

Command failed

**Comment by createcandle** [comment]
Thanks, that's really helpfull.

Perhaps we can try to recode the file.

Could you try this:

`ffmpeg -i /tmp/response.wav -vn -ac 2 -b:a 48k /tmp/response.mp3`

followed by:

`ffplay -nodisp -vn -infbuf -autoexit /tmp/response.mp3 -volume 100`

**Comment by kgiori** [comment]
Command success but no sound.

**Comment by kgiori** [comment]
Another interesting result. I plugged in a USB headset and it sounds fine. (The speed settings work too.)

**Comment by createcandle** [comment]
Yes, most USB devices work fine. The Jabra devices don't though.

Could you share the output of this command when you have the jabra plugged in?

`aplay -l`

**Comment by kgiori** [comment]
```**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: USB [Jabra SPEAK 510 USB], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

Command success

**Comment by createcandle** [comment]
Thanks. Just wanted to confirm that `1,0` was the correct device.

When you didn't hear any output with ffplay, I suspect that's because ffplay is outputting to your headphone jack. An environment variable needs to be set to test that, but I'll have to figure out how you can easily test that, if you're up for it.

**Comment by createcandle** [comment]
Could you try this?

1. Make sure there is a temporary wav file in the `/tmp` folder again by using voco, or just restarting voco.

2. Turn that wav file into an upscaled file again (I have improved this command too):

`ffmpeg -i /tmp/response.wav -vn -ar 48000 -ac 2 -sample_fmt s16 /tmp/response2.wav`

3. Play it with ffplay, but this time we force it to output over the USB device.

`SDL_AUDIODRIVER="alsa" AUDIODEV="hw:1,0" ffplay -nodisp -vn -infbuf -autoexit /tmp/response2.wav -volume 100`

**Comment by createcandle** [comment]
I've released a new version of Voco that incorporates the changes in the post above this one. It allows you to set the samplerate in the addons settings. If you set it to 48000, in theory your Jabra speaker should be happy now. Please let me know if works.

**Comment by kgiori** [comment]
48000 for the Jabra works indeed! Thank you for the fast fix @createcandle !!!

**Comment by rafiksheikh** [comment]
ffplay -nodisp -vn -infbuf -autoexit /tmp/response.wav -volume 100

Does not run, error “ /tmp/response.wav: No such file or directory  0KB sq=    0B f=0/0 “



aplay -D plughw:1,0 /tmp/response.wav -r 16000

Fails with same error as above “ /tmp/response.wav: No such file or directory “



aplay -D plughw:2,0 /tmp/response.wav -r 16000


aplay -D plughw:2,0 /tmp/response.wav -r 16000
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
aplay: main:828: audio open error: No such file or directory

**Comment by rafiksheikh** [comment]
Output of my aplay -l

aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 7/7

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

  Subdevice #4: subdevice #4

  Subdevice #5: subdevice #5

  Subdevice #6: subdevice #6

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 1: USB [Jabra SPEAK 510 USB], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

**Comment by rafiksheikh** [comment]
Sorry I didn’t check all threads. Should have first tried installing new updated.

I just tried updating Voco, it failed several times. I also tried removing it and reinstalling but for some reasons it keeps failing.

Will try again tomorrow.

Thanks!


From: Rafik Sheikh <rafiksheikh@gmail.com>
Date: Friday, 22 January 2021 at 19:03
To: createcandle/voco <reply@reply.github.com>, createcandle/voco <voco@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [createcandle/voco] Voco feedback played too fast (#19)
Output of my aplay -l

aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 7/7

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

  Subdevice #4: subdevice #4

  Subdevice #5: subdevice #5

  Subdevice #6: subdevice #6

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 1: USB [Jabra SPEAK 510 USB], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

**Comment by rafiksheikh** [comment]
Updated new version 2.5.3. No change still audio is played too fast

From: Rafik Sheikh <rafiksheikh@gmail.com>
Date: Friday, 22 January 2021 at 19:36
To: createcandle/voco <reply@reply.github.com>, createcandle/voco <voco@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [createcandle/voco] Voco feedback played too fast (#19)
Sorry I didn’t check all threads. Should have first tried installing new updated.

I just tried updating Voco, it failed several times. I also tried removing it and reinstalling but for some reasons it keeps failing.

Will try again tomorrow.

Thanks!


From: Rafik Sheikh <rafiksheikh@gmail.com>
Date: Friday, 22 January 2021 at 19:03
To: createcandle/voco <reply@reply.github.com>, createcandle/voco <voco@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [createcandle/voco] Voco feedback played too fast (#19)
Output of my aplay -l

aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 7/7

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

  Subdevice #4: subdevice #4

  Subdevice #5: subdevice #5

  Subdevice #6: subdevice #6

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 1: USB [Jabra SPEAK 510 USB], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

**Comment by kgiori** [comment]
@rafiksheikh - you have to enter "48000" in the Voco add-on configuration section called "Audio sample rate". My Jabra now works fine.

**Comment by rafiksheikh** [comment]
@kgiore

Thank you! It works fine now.

**Comment by createcandle** [comment]
Great!
