### ISSUE TITLE
custom tts and addons install path

### ISSUE THREAD

**Issue by treymarc** [createcandle/voco#2]
the tts cmd part is hardcoded in `snips/snips.toml` , in version `9.2` addons are installed in `/home/pi/.mozilla-iot/addons`

```2019-08-25 17:38:24.847 ERROR  : voco: ERROR:snips_tts_hermes: Error while trying to process event 'Say(SayMessage { text: "Do you want it to be on or off?", lang: Some("en"), id: Some("70b29f0f-cea1-476d-b8ee-c1a48a08e316"), site_id: "default", session_id: Some("036e5df9-ed9a-4b80-a554-4f7191366290") })': Can't execute `/home/pi/.mozilla/addons/voco/snips/speak.sh`
2019-08-25 17:38:24.849 ERROR  : voco:  -> caused by: No such file or directory (os error 2)```

**Comment by createcandle** [comment]
Thanks. What system are you using? What should the path be for you?

**Comment by createcandle** [comment]
'/home/pi/.mozilla/addons/voco/snips/speak.sh' should have been '/home/pi/.mozilla-iot/addons/voco/snips/speak.sh'. It has been fixed in the latest update.
