### ISSUE TITLE
Voco doesn't hear me at all, but my mic worked with Voice Control

### ISSUE THREAD

**Issue by Rudower** [createcandle/voco#22]
Hello, 

I am trying to use Voco voice control with my webthings gateway, but I encountered an issue I just can't overcome. 

I tried before with the Voice Control add on, and it could speak and hear me, so I assume that both my mic and loudspeaker work fine with my gateway. I made it to make Voice Control work with my mic by configuring the addon with "hw:CARD=Device,DEV=0". Since Voice Control had some issues, and didn't understand me, I decided to try with Voco. 

The loudspeaker with Voco works alright too, and it says "I am listening". But it doesn't seem to work with the mic: it doesn't seem to hear me at all, as its Snips thing never marks the "Sound detected" ticker. 

In the addon I've tried to switch to a different microphone setting from the default one "Attached device(1,0)", but the reconfiguration option doesn't seem to work. Whenever I choose a different option of the 4 available (1, 0) (1,1) (2,0) (2,1), either if the addon is enabled or disabled, when I try to do the change, the mic config value returns to its default configuration "Attached device(1,0)".

So, I know my mic works on my webthings gateway, but it doesn't work with Voco, and I don't know if this is due to any other issue, or if this happens because I should be able to change the mic config of the addon to another option, but I can't because after trying to change it, the mic config change doesn't work. 

Any clue? Thx a lot!

**Comment by createcandle** [comment]
Interesting. In theory it should auto-detect if you don't tell it what device to use.
- Are you running this on a Raspberry Pi? What version?
- What kind of microphone is it? USB? What brand/type? `1,0` seems to indicate the presence of a USB device.
- Do you see any indication of an error in the internal logs after you enable debugging in the addon's settings page?
- "I am listening" is just said to indicate that it is in listening mode, but it doesn't indicate that it's actually working.

**Comment by Rudower** [comment]
Hi, thanks for the response. 

It's been some time since I was thinkering with the voco addon. 

I remember that, by that time, voco told me "Hello, I'm listening". I haven't touched anything in these last few months, but when activating the voco addon now it says "Hello, listening is disabled".

I guess that does make a difference worth to share with you, but the thing is that I don't know how to enable listening, as I don't see any specific option for this, and the related options seem to be properly configured. 

Any clue? Thx again!

**Comment by createcandle** [comment]
That option is on the voco thing. After installing Voco, make sure you add the thing it provides. It has a lot of settings, such as which audio output to use.

**Comment by createcandle** [comment]
If the problem is still there, feel free to re-open this issue.
