### ISSUE TITLE
Can't find addon

### ISSUE THREAD

**Issue by Bleznudd** [createcandle/voco#23]
Hi, 

It seems like I can't find the addon through the gateway

![immagine](https://user-images.githubusercontent.com/33193871/139528423-9fe8a914-02d5-4954-ba86-a18f82424c59.png)

Is it still there?

**Comment by createcandle** [comment]
I just did a test on a fresh install, and it's still there. Do you see other addons in the list?

**Comment by Bleznudd** [comment]
I made some more test.
I can find it if I'm using the raspberry pi build, but I can't find it if I'm using boths the linux build or the docker image.

I can confirm that I see some addons, but not this one (except when using the pi)

Is this the intended behaviour?

**Comment by createcandle** [comment]
Yes this is normal. it's only available for the Raspberry Pi.
