### ISSUE TITLE
nanotts segfault

### ISSUE THREAD

**Issue by treymarc** [createcandle/voco#3]
```2019-08-25 19:08:26.187 ERROR  : voco:       3300 Segmentation fault      | ${DIR}/nanotts -l ${DIR}/lang --speed 0.9 --pitch 1.2 --volume 1 -p -m -o "$2"``` nanotts does segfault a lot. this leave the snips-audio-server not being able to play the audio and eventually the dialogue timeout

**Comment by createcandle** [comment]
Interesting. The Snips Audio Server is not supposed to play any audio.

Can you provide some more details, like which platform and version you are using? Is it a fresh image or an upgraded one?

**Comment by createcandle** [comment]
Has the latest release fixed the issue for you?
