### ISSUE TITLE
I just wanted to offer a thanks for doing this

### ISSUE THREAD

**Issue by dtaht** [createcandle/voco#5]
I am totally creeped out by all the microphones everywhere. I'd been doing good speech recognition (various tools) and output (cepstral) *for decades* prior to the explosion of AI in the cloud and being told that it was needed "out there" I simply could not believe or buy into.

thx for this tool.

**Comment by createcandle** [comment]
Thank you :-) You're very welcome.

You may enjoy this:
https://www.candlesmarthome.com/good-enough-voice-assistants
